<?php

namespace BibliothequeBundle\Repository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MytableRepository extends \Doctrine\ORM\EntityRepository
{


    public function search($request)
    {
        $qb = $this->createQueryBuilder('c');
        if($request->get('code')!='')
        {
            $qb->where('c.code_face LIKE :code')->setParameter('code','%'.$request->get('code').'%');
        }

        if($request->get('emplacement')!='')
        {
            $qb->andWhere('c.emplacement LIKE :emplacement')->setParameter('emplacement','%'.$request->get('emplacement').'%');
        }

        if($request->get('region')!='')
        {
            $qb->andWhere('c.regie LIKE :region')->setParameter('region','%'.$request->get('region').'%');
        }

        if($request->get('support')!='')
        {
            $qb->andWhere('c.support LIKE :support')->setParameter('support','%'.strtoupper($request->get('support')).'%');
        }




            $qb->orderBy('c.idface','desc');

        return $qb->getQuery()->getResult();



    }
}
